### ISSUE TITLE
Investigate running on Android

### ISSUE THREAD

**Issue by spencercarli** [spencercarli/quick-meteor-react-native#1]

**Comment by aislanmaia** [comment]
Hey @spencercarli, I've solved the problem INVALID_STATE_ERR on Android by properly configuring the object ddp. It looks like this:

```
let ddpClient = new DDPClient({
  host : "10.1.1.10", // my meteor server ip
  port : 3000, 
  ssl : false, 
  autoReconnect : true, 
  autoReconnectTimer : 500, 
  maintainCollections : true, 
  ddpVersion : '1', 
  socketConstructor: WebSocket 
});
```

Without this config, try put some console logs at connection's callback in "componentDidMount( )" to see what happens. It always output an error.

**Comment by spencercarli** [comment]
@aislanmaia glad you got this sorted out. Do you know if the `host` option has to be an IP address or can you also use `localhost` when running in the android simulator?

**Comment by verdavaine** [comment]
Hey @spencercarli, 
I always get INVALID_STATE_ERR on Android (real device or genymotion) when subscribing to the post collection: ddpClient.subscribe("posts", [], () => {...
I also get the Error message 'Cannot send a message. Unknown Websocket id 0' when calling a meteor method : ddpClient.call('addPost'); 
Only the ddpClient.connect  seems to work correctly.

**Comment by spencercarli** [comment]
@verdavaine thanks for bringing this to my attention! Could you let me know what version of React Native you're using? There were some changes to websockets in `0.20.0` and I'm wondering if they may have something to do with this.

**Comment by verdavaine** [comment]
I am using react-native 0.20.0

**Comment by spencercarli** [comment]
Hey @verdavaine I just tested this out and ran into the same issue you had. I updated the code to ensure that the error wouldn't be thrown and added some notes to the readme to get this working with Android.

Make sure to change the `host` option when initializing DDPClient to the IP address of the machine running your meteor server. For some reason `localhost` doesn't work on Android. See https://github.com/spencercarli/quick-meteor-react-native/blob/master/RNApp/app/index.js#L12

The app has been test and confirmed to work on Android now.

**Comment by verdavaine** [comment]
Thank u for you help. I confirm it's working with the server Ip address when launched inside Genymotion.  But I did not succeed no connect with a real Android device (nexus4 - Android version 5.0.1). Will try again... I had also a lot of problems using the last version of ddp-client (0.1.2) which seerms to be uncompatible. Going back to version 0.1.1 solved theses problems.

**Comment by spencercarli** [comment]
Glad to hear it's working on the sim for you! I don't have an android
device so unfortunately I can't help there.

0.1.2 is a pain. I need to figure out a better solution than ddp-client.
It's the #1 source of confusion.

On Tuesday, February 23, 2016, verdavaine notifications@github.com wrote:

> Thank u for you help. I confirm it's working with the server Ip address
> when launched inside Genymotion. But I did not succeed no connect with a
> real Android device (nexus4 - Android version 5.0.1). Will try again... I
> had also a lot of problems using the last version of ddp-client (0.1.2)
> which seerms to be uncompatible. Going back to version 0.1.1 solved theses
> problems.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spencercarli/quick-meteor-react-native/issues/1#issuecomment-188023787
> .

## 

Spencer Carli

**Comment by zainulabidin302** [comment]
When working with android, using `localhost` in host did not work for me (meteor 1.3 / react-native 0.28) but ip address did work.
Thubms up for @spencercarli
