### ISSUE TITLE
Failing to run after upgrading to react-native@0.21 on Android

### ISSUE THREAD

**Issue by bosung90** [spencercarli/quick-meteor-react-native#4]
After upgrading your project to react-native 0.21
I get runtime error on my android emulator 

> undefined is not a function (evaluating 'process.nextTick(function(_this){return function(){return _this._flush();};}(

this))')

**Comment by bosung90** [comment]
I realized this was ddp-client 0.1.2 problem.
The weird part is I tried to change to 0.1.1 and did npm install but I was kept getting same error so I thought it had something to do with react-native version.

**Comment by spencercarli** [comment]
It's odd that you still got the error after an npm install - glad you got it sorted out though! Did you have to restart the react native packager?
